### ISSUE TITLE
New System of working

### ISSUE THREAD

**Issue by pgamerx** [pgamerx/yt-dislikes-viewer#6]
I just got a DM from a user on Reddit.
They explained to me that youtube won't show the dislikes through the API either.

They gave a suggestion that maybe we as an extension should see if a user disliked the video and then show it to other users of the extension.
This is a big task but I believe it is possible

**Comment by ImNimboss** [comment]
If you're showing how many users of the extension disliked the video, then you also have to show how many users of the extension liked the video, so we can have a credible ratio
Mmh as for how big the task is, you mostly just need to have a database with a crap ton of storage because we binge youtube all day, everyday 💀

**Comment by pgamerx** [comment]
> If you're showing how many users of the extension disliked the video, then you also have to show how many users of the extension liked the video, so we can have a credible ratio
> Mmh as for how big the task is, you mostly just need to have a database with a crap ton of storage because we binge youtube all day, everyday 💀 

I can manage the data very easily by purchasing a mongoDB database. I might get funds for the same because someone said they are gonna send me the money for publishing the extension to Chrome store. 

I just need to figure out how to do this.

**Comment by ImNimboss** [comment]
Then as long as you can detect whenever one of your users likes or dislikes a video, you should be good tbh

**Comment by pgamerx** [comment]
But how tho, moreover saving it in a readable way is gonna be a pain in the ass

**Comment by ImNimboss** [comment]
Well if the project were simple then anyone could've done it
I don't know much about chrome extensions but I think it's possible to edit the HTML of a website
So, yk, you can add some HTML showing the likes and dislikes that you have from your extension users

**Comment by pgamerx** [comment]
> Well if the project were simple then anyone could've done it
> I don't know much about chrome extensions but I think it's possible to edit the HTML of a website
> So, yk, you can add some HTML showing the likes and dislikes that you have from your extension users

Main issue is knowing when user presses like and dislike

**Comment by ImNimboss** [comment]
Ah I see

**Comment by Ankh64** [comment]
possibly try contacting the youtube api on the users liked videos 
( i believe youtube stores a user's liked videos inside a playlist )

through this we can know the user didnt dislike the video. 

for storing and keeping track of the disliked videos we can make a private playlist and store the disliked videos inside it. this will mean we wouldnt need to keep track of who disliked the video on our servers. 
this system could allow for hate raids,
but i think if we store how many dislikes we got per day we could smoothen the bumps out and use the average of the total dislikes in the ratio.

**Comment by pgamerx** [comment]
Hi, thanks for suggestion.
For know I have made a replit API that will keep storing videos ID and dislike count. 
This idea can be made into a thing in future

**Comment by sripadks** [comment]
Hey there. I am trying to port this project over to Firefox and am very interested in this. So I will provide my 2 cents.

On Firefox there is an extension known as youtube watchmaker (I primarily use FF but it is likely available for chrome and its ports too I suppose) that goes through the users youtube account and browser history to mark videos as watched. Maybe you can take inspiration from that to know the disliked videos of users and use that to tally up the count in the database? This is because YT won't be providing the data anymore and as you said, we have to harvest the said data from the users of the extension.

Next will be adding a custom element that is separate from YTs dislike button as opposed to directly showing the dislikes as how it was being done till now so that it is clear that the data is only from the users of the extension as @ImNimboss mentioned.

Lastly, although I wish you and the project success, I have seen instances in the past where extensions working on youtube have been removed from chrome store. So I guess you got to be prepared for that too.

Anyhow this is just me throwing things at wall. I wish you the best as I would very much like my dislike count on the videos (or at least the semblance of it).

**Comment by pgamerx** [comment]
Problem is that something massive like this needs more than 1 or 2 developers. We have to do whatever we want to do before the 30th December. Also, as long as adblocker for YouTube is on Chrome Web store, my extension won't get removed

**Comment by ellieeet123** [comment]
> for storing and keeping track of the disliked videos we can make a private playlist and store the disliked videos inside it. this will mean we wouldnt need to keep track of who disliked the video on our servers. this system could allow for hate raids, but i think if we store how many dislikes we got per day we could smoothen the bumps out and use the average of the total dislikes in the ratio.

This would work, one idea I had to possibly make things faster is just store the video IDs of disliked videos in an array within the extention, and then just detect whenever that list changes (when the user dislikes a video) and then send the new list to the server

**Comment by TrashAccount3424** [comment]
Maybe get in touch with the Dev from https://github.com/ajayyy/SponsorBlock
His system to store crowdsourced metadata is very open and would probably work for this too.

**Comment by pgamerx** [comment]
> Maybe get in touch with the Dev from https://github.com/ajayyy/SponsorBlock
> His system to store crowdsourced metadata is very open and would probably work for this too.

Not a bad idea

**Comment by pgamerx** [comment]
Hey @sripadks, @TrashAccount3424, @ImNimboss ,and @ellieeet123 
Please visit #10 because that's our main goal now.
I will be thus closing this issue
